spring.application.name=springmodulith
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/advanced
spring.datasource.username=oddo
spring.datasource.password=oddo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
server.port=8085